# Generated by Django 5.2.7 on 2025-10-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageprovider',
            name='platform',
            field=models.CharField(choices=[('Discord', 'Discord')], default='Discord', max_length=100),
            preserve_default=False,
        ),
    ]
