# Generated by Django 5.2.7 on 2025-10-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_providers', '0002_storageprovider_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageprovider',
            name='platform',
            field=models.CharField(choices=[('Discord', 'Discord'), ('Discord_Webhook', 'Discord Webhook')], max_length=100),
        ),
    ]
