# Generated by Django 5.2.7 on 2025-10-05 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage_providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('encrypted_filename', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('encryption_key', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('storage_metadata', models.JSONField(blank=True, default=dict)),
                ('storage_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage_providers.storageprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_order', models.IntegerField()),
                ('provider_chunk_id', models.JSONField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='files.file')),
            ],
        ),
    ]
