# Generated by Django 5.2.7 on 2025-10-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunk',
            options={'ordering': ['file', 'chunk_order'], 'verbose_name': 'Chunk', 'verbose_name_plural': 'Chunks'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together={('file', 'chunk_order')},
        ),
    ]
