# Generated by Django 5.2.7 on 2025-10-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_chunk_options_alter_file_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='encrypted_filename',
            field=models.CharField(max_length=255),
        ),
    ]
