# Generated by Django 5.2.7 on 2025-10-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_encrypted_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chunk',
            old_name='provider_chunk_metadata',
            new_name='chunk_ref',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='storage_metadata',
            new_name='storage_context',
        ),
    ]
