# Generated by Django 5.1.6 on 2025-12-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_rename_provider_chunk_metadata_chunk_chunk_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sha256_signature',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
