# Generated by Django 5.2.7 on 2025-12-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_sha256_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
