# Generated by Django 5.2.7 on 2025-12-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='sha256_signature',
            new_name='client_signature',
        ),
    ]
